### ISSUE TITLE
Perform JSON content type validation in BindJSON()

### ISSUE THREAD

**Issue by falzm** [facette/httputil#1]
It might be convenient if `BindJSON()` could implicitly perform the `Content-Type: application/json` header validation instead of having to manually call `GetContentType() == "application/json"` before, WDYT?

**Comment by vbatoufflet** [comment]
Indeed, it could simplify the type validation 👍

**Comment by falzm** [comment]
Implemented in de74c01c76082fa3c24ba6b59972d9f760fab71d.
